name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Django Docker Image
        run: |
          docker build -t my-django-app ./django
          docker tag my-django-app ${{ secrets.DOCKER_HUB_USERNAME }}/my-django-app:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/my-django-app:latest

      - name: Build and Push React Docker Image
        run: |
          docker build -t my-react-app ./react
          docker tag my-react-app ${{ secrets.DOCKER_HUB_USERNAME }}/my-react-app:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/my-react-app:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker-compose down
            docker-compose pull
            docker-compose up -d
